// <auto-generated />
using System;
using BPCloud_VP.POService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPCloud_VP.POService.Migrations
{
    [DbContext(typeof(POContext))]
    [Migration("20200506134955_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCASNHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASNNumber");

                    b.Property<DateTime?>("AWBDate");

                    b.Property<string>("AWBNumber");

                    b.Property<DateTime?>("ArriveDate");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CountryOfOrigin");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("CrossWeight");

                    b.Property<DateTime?>("DepatDate");

                    b.Property<string>("DocNumber");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("NetWeight");

                    b.Property<string>("PatnerID");

                    b.Property<string>("TransportMode");

                    b.Property<string>("Type");

                    b.Property<string>("UOM");

                    b.Property<string>("VessleNumber");

                    b.Property<double>("VolumetricWeight");

                    b.Property<string>("VolumetricWeightUOM");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "ASNNumber");

                    b.ToTable("BPC_ASN_H");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCASNItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASNNumber");

                    b.Property<double>("ASNQty");

                    b.Property<string>("Batch");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<double>("CompletedQty");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DelDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Item");

                    b.Property<string>("ManfCountry");

                    b.Property<DateTime?>("ManfDate");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PatnerID");

                    b.Property<double>("TransitQty");

                    b.Property<string>("Type");

                    b.Property<string>("UOM");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "ASNNumber", "Item");

                    b.ToTable("BPC_ASN_I");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCFLIPCost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("ExpenceType");

                    b.Property<string>("FLIPID");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<string>("Remarks");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "FLIPID", "ExpenceType");

                    b.ToTable("BPC_FLIP_Cost");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCFLIPHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("FLIPID");

                    b.Property<double>("InvoiceAmount");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<string>("InvoiceNumber");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "FLIPID");

                    b.ToTable("BPC_FLIP_H");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCFLIPItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DelDate");

                    b.Property<string>("FLIPID");

                    b.Property<string>("HSN");

                    b.Property<double>("InvoiceQty");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Item");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OpenQty");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PatnerID");

                    b.Property<string>("Type");

                    b.Property<string>("UOM");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "FLIPID", "Item");

                    b.ToTable("BPC_FLIP_I");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCOFGRGI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DelDate");

                    b.Property<string>("DocNumber");

                    b.Property<string>("GRGIDoc");

                    b.Property<double>("GRGIQty");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Item");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<string>("ShippingDoc");

                    b.Property<string>("ShippingPartner");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "DocNumber", "GRGIDoc", "Item");

                    b.ToTable("BPC_OF_GRGI");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCOFHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AckDate");

                    b.Property<string>("AckRemark");

                    b.Property<string>("AckStatus");

                    b.Property<string>("AckUser");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("CrossAmount");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("DocDate");

                    b.Property<string>("DocNumber");

                    b.Property<string>("DocVersion");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("NetAmount");

                    b.Property<string>("PINNumber");

                    b.Property<string>("PatnerID");

                    b.Property<string>("RefDoc");

                    b.Property<string>("Status");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "DocNumber");

                    b.ToTable("BPC_OF_H");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCOFItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AckDelDate");

                    b.Property<string>("AckStatus");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<double>("CompletedQty");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DelDate");

                    b.Property<string>("DocNumber");

                    b.Property<string>("HSN");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsClosed");

                    b.Property<string>("Item");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OpenQty");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PatnerID");

                    b.Property<double>("TransitQty");

                    b.Property<string>("Type");

                    b.Property<string>("UOM");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "DocNumber", "Item");

                    b.ToTable("BPC_OF_I");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCOFQM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocNumber");

                    b.Property<double>("GRGIQty");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Item");

                    b.Property<double>("LotQty");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<double>("RejQty");

                    b.Property<string>("RejReason");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "DocNumber", "Item");

                    b.ToTable("BPC_OF_QM");
                });

            modelBuilder.Entity("BPCloud_VP.POService.Models.BPCOFScheduleLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AckDelDate");

                    b.Property<string>("AckStatus");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DelDate");

                    b.Property<string>("DocNumber");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Item");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PatnerID");

                    b.Property<string>("SlLine");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("Client", "Company", "Type", "PatnerID", "DocNumber", "Item", "SlLine");

                    b.ToTable("BPC_OF_SL");
                });
#pragma warning restore 612, 618
        }
    }
}
