// <auto-generated />
using System;
using BPCloud_VP_POService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPCloud_VP_POService.Migrations
{
    [DbContext(typeof(POContext))]
    partial class POContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCASNFieldMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DefaultValue");

                    b.Property<string>("Field");

                    b.Property<string>("FieldName");

                    b.Property<bool>("Invisible");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("Mandatory");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("Field");

                    b.ToTable("BPC_ASN_Field_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCASNHeader", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("ASNNumber")
                        .HasMaxLength(12);

                    b.Property<DateTime?>("ASNDate");

                    b.Property<DateTime?>("AWBDate");

                    b.Property<string>("AWBNumber");

                    b.Property<double?>("AccessibleValue");

                    b.Property<DateTime?>("ArrivalDate");

                    b.Property<int>("ArrivalDateInterval");

                    b.Property<string>("BillOfLading")
                        .HasMaxLength(20);

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(40);

                    b.Property<string>("ContactPersonNo")
                        .HasMaxLength(14);

                    b.Property<string>("CountryOfOrigin");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DepartureDate");

                    b.Property<string>("DocNumber");

                    b.Property<string>("Field1");

                    b.Property<string>("Field10");

                    b.Property<string>("Field2");

                    b.Property<string>("Field3");

                    b.Property<string>("Field4");

                    b.Property<string>("Field5");

                    b.Property<string>("Field6");

                    b.Property<string>("Field7");

                    b.Property<string>("Field8");

                    b.Property<string>("Field9");

                    b.Property<double?>("GrossWeight");

                    b.Property<string>("GrossWeightUOM");

                    b.Property<string>("InvDocReferenceNo");

                    b.Property<double?>("InvoiceAmount");

                    b.Property<string>("InvoiceAmountUOM");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<string>("InvoiceNumber");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSubmitted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double?>("NetWeight");

                    b.Property<string>("NetWeightUOM");

                    b.Property<int?>("NumberOfPacks");

                    b.Property<double?>("POBasicPrice");

                    b.Property<string>("ShippingAgency");

                    b.Property<string>("Status");

                    b.Property<double?>("TaxAmount");

                    b.Property<string>("TransportMode");

                    b.Property<string>("TransporterName")
                        .HasMaxLength(40);

                    b.Property<string>("VessleNumber");

                    b.Property<double?>("VolumetricWeight");

                    b.Property<string>("VolumetricWeightUOM");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "ASNNumber");

                    b.ToTable("BPC_ASN_H");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCASNItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("ASNNumber")
                        .HasMaxLength(12);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<double>("ASNQty");

                    b.Property<string>("Batch");

                    b.Property<double>("CompletedQty");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<DateTime?>("ExpiryDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ManufactureCountry");

                    b.Property<DateTime?>("ManufactureDate");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OpenQty");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PlantCode");

                    b.Property<double?>("TaxAmount");

                    b.Property<string>("TaxCode");

                    b.Property<double>("TransitQty");

                    b.Property<string>("UOM");

                    b.Property<double?>("UnitPrice");

                    b.Property<double?>("Value");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "ASNNumber", "Item");

                    b.ToTable("BPC_ASN_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCASNPack", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("ASNNumber")
                        .HasMaxLength(12);

                    b.Property<string>("PackageID")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Dimension");

                    b.Property<double?>("GrossWeight");

                    b.Property<string>("GrossWeightUOM");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double?>("NetWeight");

                    b.Property<string>("NetWeightUOM");

                    b.Property<string>("ReferenceNumber");

                    b.Property<double?>("VolumetricWeight");

                    b.Property<string>("VolumetricWeightUOM");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "ASNNumber", "PackageID");

                    b.ToTable("BPC_ASN_Pack");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCAttachment", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("AttachmentFile");

                    b.Property<string>("AttachmentName");

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<long>("ContentLength");

                    b.Property<string>("ContentType");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<string>("ReferenceNo");

                    b.Property<string>("Type");

                    b.HasKey("AttachmentID");

                    b.ToTable("BPCAttachments");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCCEOMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEOMessage");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsReleased");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("MessageID");

                    b.ToTable("BPC_CEO_Message");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCCountryMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("ID");

                    b.ToTable("BPC_Country_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCCurrencyMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CurrencyCode");

                    b.Property<string>("CurrencyName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("ID");

                    b.ToTable("BPC_Currency_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCDocumentCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASNNumber");

                    b.Property<string>("AttachmentReferenceNo");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocumentTitle");

                    b.Property<string>("DocumentType");

                    b.Property<string>("Filename");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("ID");

                    b.ToTable("BPC_DocumentCenter");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCDocumentCenterMaster", b =>
                {
                    b.Property<string>("DocumentType")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Extension");

                    b.Property<string>("ForwardMail");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("Mandatory");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("SizeInKB");

                    b.Property<string>("Text");

                    b.HasKey("DocumentType");

                    b.HasAlternateKey("AppID");

                    b.ToTable("BPC_DocumentCenter_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCExpenseTypeMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<string>("Company");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("ExpenseType");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MaxAmount");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PatnerID");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("BPC_ExpenseType_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCFLIPAttachment", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("AttachmentFile");

                    b.Property<string>("AttachmentName");

                    b.Property<long>("ContentLength");

                    b.Property<string>("ContentType");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PO");

                    b.HasKey("AttachmentID");

                    b.ToTable("BPC_FLIP_Attachment");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCFLIPCost", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FLIPID")
                        .HasMaxLength(12);

                    b.Property<string>("ExpenceType")
                        .HasMaxLength(1);

                    b.Property<double>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Remarks");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "FLIPID", "ExpenceType");

                    b.ToTable("BPC_FLIP_Cost");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCFLIPHeader", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FLIPID")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocNumber");

                    b.Property<double?>("InvoiceAmount");

                    b.Property<string>("InvoiceAttachmentName");

                    b.Property<string>("InvoiceCurrency");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<string>("InvoiceDocID");

                    b.Property<string>("InvoiceNumber");

                    b.Property<string>("InvoiceType");

                    b.Property<bool>("IsActive");

                    b.Property<string>("IsInvoiceFlag");

                    b.Property<string>("IsInvoiceOrCertified");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "FLIPID");

                    b.ToTable("BPC_FLIP_H");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCFLIPItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FLIPID")
                        .HasMaxLength(12);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<double>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<string>("HSN");

                    b.Property<double>("InvoiceQty");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OpenQty");

                    b.Property<double>("OrderedQty");

                    b.Property<double>("Price");

                    b.Property<double>("Tax");

                    b.Property<string>("UOM");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "FLIPID", "Item");

                    b.ToTable("BPC_FLIP_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCInvoice", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(16);

                    b.Property<string>("AttID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("DateofPayment");

                    b.Property<double>("InvoiceAmount");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PODConfirmedBy");

                    b.Property<DateTime?>("PODDate");

                    b.Property<double>("PaidAmount");

                    b.Property<string>("PoReference");

                    b.Property<string>("Status");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "FiscalYear", "InvoiceNo");

                    b.ToTable("BPC_INV");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCInvoiceItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(16);

                    b.Property<string>("Item")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("InvoiceQty");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("PODQty");

                    b.Property<string>("ReasonCode");

                    b.Property<string>("Status");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "FiscalYear", "InvoiceNo", "Item");

                    b.ToTable("BPC_INV_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFAIACT", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("SeqNo")
                        .HasMaxLength(4);

                    b.Property<string>("ActionText");

                    b.Property<string>("AppID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("DocNumber");

                    b.Property<bool>("HasSeen");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Status");

                    b.Property<string>("Time");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "SeqNo");

                    b.ToTable("BPC_OF_AI_ACT");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFGRGI", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(10);

                    b.Property<string>("GRGIDoc")
                        .HasMaxLength(10);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<string>("Description");

                    b.Property<double>("GRGIQty");

                    b.Property<DateTime?>("GRIDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("ShippingDoc");

                    b.Property<string>("ShippingPartner");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber", "GRGIDoc", "Item");

                    b.ToTable("BPC_OF_GRGI");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFHeader", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("AckDate");

                    b.Property<string>("AckRemark");

                    b.Property<string>("AckStatus");

                    b.Property<string>("AckUser");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("CrossAmount");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("DocDate");

                    b.Property<string>("DocType");

                    b.Property<string>("DocVersion");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("NetAmount");

                    b.Property<string>("PINNumber");

                    b.Property<string>("PlantName");

                    b.Property<string>("RefDoc");

                    b.Property<string>("Status");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber");

                    b.ToTable("BPC_OF_H");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(10);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<DateTime?>("AckDeliveryDate");

                    b.Property<string>("AckStatus");

                    b.Property<double>("CompletedQty");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<string>("HSN");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsClosed");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OpenQty");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("PlantCode");

                    b.Property<double?>("TaxAmount");

                    b.Property<string>("TaxCode");

                    b.Property<double>("TransitQty");

                    b.Property<string>("UOM");

                    b.Property<double?>("UnitPrice");

                    b.Property<double?>("Value");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber", "Item");

                    b.ToTable("BPC_OF_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFQM", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(12);

                    b.Property<string>("Item")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("GRGIQty");

                    b.Property<bool>("IsActive");

                    b.Property<double>("LotQty");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("RejQty");

                    b.Property<string>("RejReason");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber", "Item");

                    b.ToTable("BPC_OF_QM");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFScheduleLine", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(10);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<string>("SlLine")
                        .HasMaxLength(4);

                    b.Property<DateTime?>("AckDeliveryDate");

                    b.Property<string>("AckStatus");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OrderedQty");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber", "Item", "SlLine");

                    b.ToTable("BPC_OF_SL");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCOFSubcon", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("DocNumber")
                        .HasMaxLength(10);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<string>("SlLine")
                        .HasMaxLength(4);

                    b.Property<string>("Batch");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("Date");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("OrderedQty");

                    b.Property<string>("Remarks");

                    b.Property<string>("Status");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "DocNumber", "Item", "SlLine");

                    b.ToTable("BPC_OF_Subcon");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPayAccountStatement", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PartnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("DocumentID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("CreditAmount");

                    b.Property<double>("DebitAmount");

                    b.Property<DateTime?>("DocumentDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ItemText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime?>("PostingDate");

                    b.Property<string>("RefID");

                    b.HasKey("Client", "Company", "Type", "PartnerID", "FiscalYear", "DocumentID");

                    b.ToTable("BPC_PAY_AS");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPayPayable", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PartnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("Invoice")
                        .HasMaxLength(16);

                    b.Property<double>("AdvAmount");

                    b.Property<double>("Amount");

                    b.Property<double>("Balance");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("DueDate");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime?>("PostedOn");

                    b.HasKey("Client", "Company", "Type", "PartnerID", "FiscalYear", "Invoice");

                    b.ToTable("BPC_PAY_PAYABLE");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPayPayment", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PartnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(10);

                    b.Property<string>("BankAccount");

                    b.Property<string>("BankName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("PaidAmount");

                    b.Property<DateTime?>("PaymentDate");

                    b.Property<string>("PaymentType");

                    b.HasKey("Client", "Company", "Type", "PartnerID", "FiscalYear", "DocumentNumber");

                    b.ToTable("BPC_PAY_PAYMENT");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPayTDS", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PartnerID")
                        .HasMaxLength(12);

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(4);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("DocumentID");

                    b.Property<double>("BaseAmount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime?>("PostingDate");

                    b.Property<double>("TDSAmount");

                    b.Property<string>("TDSCategory");

                    b.HasKey("Client", "Company", "Type", "PartnerID", "FiscalYear", "CompanyCode", "DocumentID");

                    b.ToTable("BPC_PAY_TDS");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPIHeader", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("PIRNumber")
                        .HasMaxLength(12);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("DocumentNumber");

                    b.Property<double?>("GrossAmount");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double?>("NetAmount");

                    b.Property<string>("PIRType");

                    b.Property<string>("ReferenceDoc");

                    b.Property<string>("Status");

                    b.Property<string>("Text");

                    b.Property<string>("UOM");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "PIRNumber");

                    b.ToTable("BPC_PI_H");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPIItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("PIRNumber")
                        .HasMaxLength(12);

                    b.Property<string>("Item")
                        .HasMaxLength(4);

                    b.Property<string>("AttachmentReferenceNo");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<string>("FileName");

                    b.Property<string>("HSN");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MaterialText");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double?>("OrderQty");

                    b.Property<string>("ProdcutID");

                    b.Property<string>("ReasonText");

                    b.Property<double?>("RetQty");

                    b.Property<string>("UOM");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "PIRNumber", "Item");

                    b.ToTable("BPC_PI_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPlantMaster", b =>
                {
                    b.Property<string>("PlantCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PinCode");

                    b.Property<string>("PlantText");

                    b.Property<string>("State");

                    b.HasKey("PlantCode");

                    b.ToTable("BPC_Plant_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPODHeader", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("InvoiceNumber");

                    b.Property<double?>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<string>("DocNumber");

                    b.Property<DateTime?>("InvoiceDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Status");

                    b.Property<string>("Transporter");

                    b.Property<string>("TruckNumber");

                    b.Property<string>("VessleNumber");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "InvoiceNumber");

                    b.ToTable("BPC_POD_H");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCPODItem", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("PatnerID")
                        .HasMaxLength(12);

                    b.Property<string>("InvoiceNumber");

                    b.Property<string>("Item");

                    b.Property<double?>("AcceptedQty");

                    b.Property<string>("AttachmentName");

                    b.Property<string>("AttachmentReferenceNo");

                    b.Property<double?>("BreakageQty");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocNumber");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Material");

                    b.Property<string>("MaterialText");

                    b.Property<double?>("MissingQty");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("Qty");

                    b.Property<string>("Reason");

                    b.Property<double?>("ReceivedQty");

                    b.Property<string>("Remarks");

                    b.HasKey("Client", "Company", "Type", "PatnerID", "InvoiceNumber", "Item");

                    b.ToTable("BPC_POD_I");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCProd", b =>
                {
                    b.Property<string>("Client")
                        .HasMaxLength(3);

                    b.Property<string>("Company")
                        .HasMaxLength(4);

                    b.Property<string>("Type")
                        .HasMaxLength(1);

                    b.Property<string>("ProductID")
                        .HasMaxLength(12);

                    b.Property<string>("AttID");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Stock");

                    b.Property<DateTime?>("StockUpdatedOn");

                    b.Property<string>("Text");

                    b.Property<string>("UOM");

                    b.HasKey("Client", "Company", "Type", "ProductID");

                    b.ToTable("BPC_Prod");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCReasonMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("ReasonCode");

                    b.Property<string>("ReasonText");

                    b.HasKey("ID");

                    b.ToTable("BPC_Reason_Master");
                });

            modelBuilder.Entity("BPCloud_VP_POService.Models.BPCSCOCMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsReleased");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("SCOCMessage");

                    b.HasKey("MessageID");

                    b.ToTable("BPC_SCOC_Message");
                });
#pragma warning restore 612, 618
        }
    }
}
